[package]
name = "rusty_dumb_tools"
version = "0.1.0"
edition = "2021"
description = "A collection of simply tools."
repository = "https://github.com/trevorwslee/rusty_dumb_tools"
license = "MIT"
exclude = [".vscode", ".ignore"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
