[package]
name = "rusty_dumb_tools"
version = "0.1.2"
edition = "2021"
description = "A collection of simply tools Rust modules."
repository = "https://github.com/trevorwslee/rusty_dumb_tools"
license = "MIT"
keywords = ["arg_parser", "calc_processor"]
categories = ["command-line-utilities"]
readme = "README.md"
exclude = [".vscode", ".ignore"]


[dependencies]
iced = {version="0.10",features=["canvas", "tokio", "debug"]}
time = { version = "0.3", features = ["local-offset"] }