[package]
name = "rusty_dumb_calculator_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
rusty_dumb_tools = {version = "0.1.5", path = "../.." }
